# Generated by Django 3.2.16 on 2022-11-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
